# Generated by Django 3.0.7 on 2020-06-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskapp', '0008_auto_20200607_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='is_token_granted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='is_token_purchased',
            field=models.BooleanField(default=1),
        ),
    ]
