# Generated by Django 3.0.7 on 2020-06-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskapp', '0009_auto_20200608_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='is_token_granted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='is_token_purchased',
            field=models.BooleanField(),
        ),
    ]
