# Generated by Django 3.0.7 on 2020-06-08 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deskapp', '0010_auto_20200608_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantedToken',
            fields=[
                ('session', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('token_amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='is_token_granted',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='is_token_purchased',
        ),
        migrations.CreateModel(
            name='TokenPlayLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens_playing_for', models.IntegerField()),
                ('tokens_won', models.IntegerField()),
                ('tokens_remaining', models.IntegerField()),
                ('won_on_number', models.IntegerField(blank=True, null=True)),
                ('is_jackpot', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='deskapp.GrantedToken')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
