# Generated by Django 3.0.7 on 2020-06-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deskapp', '0012_auto_20200609_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenplaylog',
            name='remarks',
            field=models.CharField(default='Tokens refilled from game console', max_length=255),
            preserve_default=False,
        ),
    ]
